### ISSUE TITLE
Integrity Error when posting the same job title for a given company

### ISSUE THREAD

**Issue by MarysiaLowas** [djangogirlsjobs/djangogirls#14]
Steps to reproduce:
1. Add a job for a company.
2. Add a new job with the same job title for the same company.

As we assumed that a given company cannot post two jobs with the same title, we've got the Integrity Error here. We need to add a validation that will check that before submitting the form and display an appropriate message.

**Comment by rebkwok** [comment]
Same for meetups with same title/city

**Comment by MarysiaLowas** [comment]
Sorted for now by removing a separate model for Companies
