### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by rebkwok** [djangogirlsjobs/djangogirls#28]
Test coverage is down at 71%; need to review the coverage reports and add tests to cover the major areas that are missing.  From the last coverage report on master, the worst culprits are admin.py which only has 54% coverage, and populate_database.py which is 0%.  Views are at 81%, models at 97%, forms and urls at 100%.

**Comment by MarysiaLowas** [comment]
first test for the admin site PRed..

**Comment by MarysiaLowas** [comment]
more test coming in #48

**Comment by aniav** [comment]
This issue was moved to DjangoGirls/djangogirls#164
