### ISSUE TITLE
Complete the job offer text with visitor numbers

### ISSUE THREAD

**Issue by rebkwok** [djangogirlsjobs/djangogirls#37]
The job offer and meetup form introductions currently have a line that refers to "XXX beginners"; need to fill this in with the relevant number or reword the text so we don't need it
https://github.com/djangogirlsjobs/djangogirls/blob/master/templates/jobs/job_edit.html#L23
https://github.com/djangogirlsjobs/djangogirls/blob/master/templates/jobs/meetup_edit.html#L27

**Comment by MarysiaLowas** [comment]
rephrased - I've pull it in a sec
