### ISSUE TITLE
Remove loreum ipsum in templates

### ISSUE THREAD

**Issue by rebkwok** [djangogirlsjobs/djangogirls#38]
Remove the testing code that adds loreum ipsum to templates for job/meetup descriptions

https://github.com/djangogirlsjobs/djangogirls/blob/master/templates/jobs/job_details.html#L39
https://github.com/djangogirlsjobs/djangogirls/blob/master/templates/jobs/meetup_details.html#L38

**Comment by MarysiaLowas** [comment]
I've corrected it locally and I'll pull it in the the next PR.

**Comment by MarysiaLowas** [comment]
@rebkwok This issue can be closed as well.
