### ISSUE TITLE
Change "job offer" to "job opportunity."

### ISSUE THREAD

**Issue by williln** [djangogirlsjobs/djangogirls#49]
These companies won't be guaranteeing Django Girls a job, they are just posting the job they have available, right? A "job offer" is when someone actually offers you a job, so we should change this to "job opportunity" or "job listings" throughout, to avoid confusion.

**Comment by ksiedlarek** [comment]
I am a bit lost. What should I put in places like "Publishing an offer..." ?

**Comment by williln** [comment]
@ksiedlarek I would say, "Publishing a job opportunity" or "Publishing a job listing" in that case.
