### ISSUE TITLE
No error on incomplete email address

### ISSUE THREAD

**Issue by williln** [djangogirlsjobs/djangogirls#51]
When I put in `test` as the email address, I get an error that I should have an `@` in the email address. 

When I correct it by just doing `test@test`, the page just reloads upon submission without an error message. I can correct the email to be `test@test.com` and then it will submit, but nothing ever tells me to do that.

**Comment by williln** [comment]
More notes: This seems to be a general problem with error handling (in Chrome on a Mac, anyway); the errors are there, but they are only a slightly different grey than the regular text. Some errors appear as inline validation (i.e., the email missing an "@"), but others are just text below the box. This doesn't call your attention to the errors, so they are easy to miss. 

Make the error messages a brighter color (possibly red?) so they stand out and people can easily see what to correct. See below. 

<img width="421" alt="screen shot 2015-07-15 at 12 38 07 pm" src="https://cloud.githubusercontent.com/assets/2286304/8708054/918e8f96-2aee-11e5-9cfc-939b34e45ff2.png">

**Comment by williln** [comment]
The same thing happens on the add a meetup page-- the error messages are just gray, and that's hard to notice.

**Comment by MarysiaLowas** [comment]
To improve it, we can add CRISPY_TEMPLATE_PACK = 'bootstrap3' to settings.py. It makes the error fields red. I'm working on it at the moment.
