### ISSUE TITLE
Cities/country confusion

### ISSUE THREAD

**Issue by williln** [djangogirlsjobs/djangogirls#53]
The label for "Cities" is plural, but the label for "Country" is singular. Is the intent that if the position is in multiple cities, they should all be entered, separated by a comma? What if the company has openings also in multiple countries?

**Comment by MarysiaLowas** [comment]
With "Cities", it is exactly as you said - you can add multiple cities after a comma, or in fact anything, as we are not parsing them. We haven't thought about different countries...

**Comment by ksiedlarek** [comment]
We did think about it at the very end of our hangout with Ania. The conclusion was, probably when someone wants to add event in multiple cities it would be in one country (probably if it was international then chances are high that contact emails, dates, sites, will be different and there should be separate events).

**Comment by williln** [comment]
I think some help text for that would be helpful. "If you have opportunities in several countries, please either specify that in the job description, or add job opportunities for each country in which you have a space," or something.
