### ISSUE TITLE
What do you mean by "You need to show us that you care about improving diversity?"

### ISSUE THREAD

**Issue by williln** [djangogirlsjobs/djangogirls#57]
So you have this statement: "You need to show us that you care about improving diversity." But how do they show you that? How is that determined? I think it's confusing to have a statement like that without an input that corresponds to them demonstrating some sort of commitment to diversity. Then, it seems like we will reject their job posting if we don't personally know them/the company. 

Do we want to add some sort of "for reviewers/admins eyes only" that has them tell us something about diversity? Do we just assume that if they are sending this into us, that they care about diversity? If the latter, we should remove this sentence, because it's not serving a purpose.

**Comment by ksiedlarek** [comment]
I think we assume that they care about diversity, I have no idea how could they prove it is true.

**Comment by williln** [comment]
So in that case @ksiedlarek I'd either cut the sentence or change it to, "By submitting a job opportunity to us, you're demonstrating that you care about diversity in your workplace and in the tech community in general. Thank you!"

**Comment by ksiedlarek** [comment]
ok.

**Comment by williln** [comment]
Opened PR #63 for this. Let me know what you think!
